# Generated by Django 5.2.5 on 2025-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KanjiWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kanji", models.CharField(max_length=10)),
                ("reading", models.CharField(max_length=20)),
            ],
        ),
    ]
